name: C/C++ CI

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: clang-format lint
      run: find -type f -name "*.c" -o -type f -name "*.h" -exec ./tests/lint.sh {} \;
