name: Code Quality

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        echo "" | sudo add-apt-repository ppa:snaipewastaken/ppa
        sudo apt update
        sudo apt install -y clang-tidy libcriterion-dev

    - name: clang-format lint
      run: find -type f -name "*.c" -o -type f -name "*.h" -exec ./tests/lint.sh {} \;

    - name: run unit-tests
      run: make test
