name: Unit tests

on: push
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    # needed for criterion
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2

    - name: run utests
      run: make test
